# Generated by Django 4.2.23 on 2025-08-08 14:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_message_id', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=1024)),
                ('body', models.TextField()),
                ('received_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('succes', models.BooleanField()),
                ('major_error', models.BooleanField()),
                ('error', models.TextField(blank=True, null=True)),
                ('execution_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_ctrk', models.URLField(unique=True)),
                ('redirected_url', models.URLField()),
                ('general_url', models.URLField()),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('visits_by_users', models.ManyToManyField(related_name='visited_urls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stores', models.JSONField(default=list, help_text='JSON list of subscribed store IDs')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full store name', max_length=255, verbose_name='Store Name')),
                ('email_addresses', models.TextField()),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('home_url', models.URLField()),
                ('sale_url', models.URLField(blank=True, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255)),
                ('domain_list', models.JSONField(blank=True, null=True)),
                ('isVerified', models.BooleanField(default=False)),
                ('genderPreferenceSet', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('B', 'Both')], max_length=1, null=True)),
                ('mayUseContent', models.BooleanField(default=False)),
                ('dateIssued', models.DateTimeField(default=datetime.datetime(2025, 8, 8, 14, 31, 32, 523674, tzinfo=datetime.timezone.utc))),
                ('subscriptions', models.ManyToManyField(blank=True, related_name='subscribed_stores', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GmailSaleAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sale_mail', models.BooleanField()),
                ('is_personal_deal', models.BooleanField()),
                ('title', models.TextField(blank=True, null=True)),
                ('grabber', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('main_link', models.TextField(blank=True, null=True)),
                ('highlighted_products', models.JSONField(blank=True, null=True)),
                ('deal_probability', models.FloatField()),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='deals.gmailmessage')),
            ],
        ),
        migrations.AddField(
            model_name='gmailmessage',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals.store'),
        ),
    ]
