# Generated by Django 4.2.23 on 2025-08-08 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='dateIssued',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 8, 15, 59, 6, 247231, tzinfo=datetime.timezone.utc)),
        ),
    ]
