# Generated by Django 4.2.23 on 2025-08-09 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_alter_store_dateissued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='dateIssued',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 9, 14, 18, 36, 534938, tzinfo=datetime.timezone.utc)),
        ),
    ]
