# Generated by Django 4.2.23 on 2025-08-10 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_alter_store_dateissued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='dateIssued',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 10, 7, 56, 11, 615372, tzinfo=datetime.timezone.utc)),
        ),
    ]
