# Generated by Django 4.2.23 on 2025-08-10 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_alter_store_dateissued'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailmessage',
            name='email_to',
            field=models.CharField(default='gijsgprojects@gmail.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='store',
            name='dateIssued',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 10, 11, 8, 27, 990113, tzinfo=datetime.timezone.utc)),
        ),
    ]
