# Generated by Django 4.2.23 on 2025-08-10 11:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_gmailmessage_email_to_alter_store_dateissued'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmailmessage',
            name='in_analysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gmailsaleanalysis',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='deals.gmailmessage'),
        ),
        migrations.AlterField(
            model_name='store',
            name='dateIssued',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 10, 11, 27, 55, 362936, tzinfo=datetime.timezone.utc)),
        ),
    ]
