# Generated by Django 4.2.23 on 2025-08-10 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_gmailmessage_in_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='dateIssued',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 10, 13, 13, 40, 86627, tzinfo=datetime.timezone.utc)),
        ),
    ]
