# Generated by Django 4.2.23 on 2025-08-12 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_alter_store_dateissued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='dateIssued',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 12, 13, 23, 26, 61897, tzinfo=datetime.timezone.utc)),
        ),
    ]
