# Generated by Django 4.2.23 on 2025-08-13 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0010_alter_store_dateissued'),
    ]

    operations = [
        migrations.CreateModel(
            name='GmailToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('token_json', models.JSONField()),
                ('credentials_json', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='store',
            name='dateIssued',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 13, 12, 14, 1, 64287, tzinfo=datetime.timezone.utc)),
        ),
    ]
