# Generated by Django 4.2.23 on 2025-08-10 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='API_Errors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('error', models.CharField(max_length=255)),
                ('execution_date', models.DateTimeField(default=datetime.datetime(2025, 8, 10, 7, 56, 11, 618484, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
