# Generated by Django 4.2.23 on 2025-08-10 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_errors',
            name='execution_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 10, 11, 8, 27, 994736, tzinfo=datetime.timezone.utc)),
        ),
    ]
