# Generated by Django 4.2.23 on 2025-08-10 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_api_errors_execution_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_errors',
            name='execution_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 10, 11, 27, 55, 367843, tzinfo=datetime.timezone.utc)),
        ),
    ]
