# Generated by Django 4.2.23 on 2025-08-10 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_api_errors_execution_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_errors',
            name='execution_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 10, 13, 13, 40, 91153, tzinfo=datetime.timezone.utc)),
        ),
    ]
