# Generated by Django 4.2.23 on 2025-08-12 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_api_errors_execution_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='API_Errors_Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('error', models.CharField(max_length=255)),
                ('execution_date', models.DateTimeField(default=datetime.datetime(2025, 8, 12, 11, 3, 42, 192309, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.AlterField(
            model_name='api_errors',
            name='execution_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 12, 11, 3, 42, 191865, tzinfo=datetime.timezone.utc)),
        ),
    ]
