# Generated by Django 4.2.23 on 2025-08-12 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_api_errors_site_alter_api_errors_execution_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_errors',
            name='execution_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 12, 11, 26, 45, 38125, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='api_errors_site',
            name='execution_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 12, 11, 26, 45, 38669, tzinfo=datetime.timezone.utc)),
        ),
    ]
