# Generated by Django 4.2.23 on 2025-08-12 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_api_errors_execution_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_errors',
            name='execution_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 12, 13, 23, 26, 67784, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='api_errors_site',
            name='execution_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 12, 13, 23, 26, 68336, tzinfo=datetime.timezone.utc)),
        ),
    ]
