# Generated by Django 4.2.23 on 2025-10-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemessage',
            name='isReviewed',
            field=models.BooleanField(default=False),
        ),
    ]
