# Generated by Django 4.2.23 on 2025-10-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_salemessage_isreviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemessage',
            name='link',
            field=models.URLField(default='www.example.com'),
            preserve_default=False,
        ),
    ]
