# Generated by Django 4.2.23 on 2025-10-23 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0003_salemessage_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemessage',
            name='created_by',
            field=models.ForeignKey(default=58, on_delete=django.db.models.deletion.CASCADE, related_name='salemessages', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
