# Generated by Django 4.2.23 on 2025-10-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_salemessage_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemessage',
            name='needsManualReview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salemessage',
            name='publicReady',
            field=models.BooleanField(default=False),
        ),
    ]
