# Generated by Django 4.2.23 on 2025-10-30 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_salemessage_needsmanualreview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroqAPIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_safe', models.BooleanField()),
                ('reason', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('moderated_at', models.DateTimeField(auto_now_add=True)),
                ('salemessage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='groq_data', to='business.salemessage')),
            ],
        ),
    ]
