# Generated by Django 4.2.23 on 2025-10-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_groqapidata'),
    ]

    operations = [
        migrations.AddField(
            model_name='salemessage',
            name='isManualReviewed',
            field=models.BooleanField(default=False),
        ),
    ]
