# Generated by Django 4.2.23 on 2025-10-31 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_salemessage_ismanualreviewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditProfileRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('image_url', models.CharField(blank=True, max_length=255)),
                ('business_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_requests', to='business.businessprofile')),
            ],
        ),
    ]
