# Generated by Django 4.2.23 on 2025-11-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_editprofilerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editprofilerequest',
            name='description',
            field=models.TextField(blank=True, max_length=175, null=True),
        ),
        migrations.AlterField(
            model_name='salemessage',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='salemessage',
            name='grabber',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='salemessage',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
