# Generated by Django 4.2.23 on 2025-11-01 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0009_alter_editprofilerequest_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleMessageClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('salemessage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='business.salemessage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_made_salemessage_clicks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
